// mockData.js
const mockPlaces = [
  "Kuala Lumpur, Malaysia",
  "Penang, Malaysia",
  "Johor Bahru, Malaysia",
  "Malacca City, Malaysia",
  "Ipoh, Malaysia",
  "Kota Kinabalu, Malaysia",
  "Kuching, Malaysia",
  "Shah Alam, Malaysia",
  "George Town, Malaysia",
  "Petaling Jaya, Malaysia",
  "Subang Jaya, Malaysia",
  "Kuantan, Malaysia",
  "Klang, Malaysia",
  "Terengganu, Malaysia",
  "Langkawi, Malaysia",
  "Miri, Malaysia",
  "Alor Setar, Malaysia",
  "Taiping, Malaysia",
  "Sibu, Malaysia",
  "Melaka, Malaysia",
  "Sandakan, Malaysia",
  "Seremban, Malaysia",
  "Butterworth, Malaysia",
  "Batu Pahat, Malaysia",
  "Kulim, Malaysia",
  "Lahad Datu, Malaysia",
  "Bintulu, Malaysia",
  "Kuala Terengganu, Malaysia",
  "Kudat, Malaysia",
  "Tawau, Malaysia",
  "Muar, Malaysia",
  "Kluang, Malaysia",
  "Pontian Kechil, Malaysia",
  "Perai, Malaysia",
  "Tasek Glugor, Malaysia",
  "Kampung Sungai Ara, Malaysia",
  "Kampung Baru Subang, Malaysia",
  "Kampung Bukit Baharu, Malaysia",
  "Kampung Pasir Gudang Baru, Malaysia",
  "Kampung Baharu Nilai, Malaysia",
  "Kampung Bukit Baru, Malaysia",
  "Kampung Baru Kundang, Malaysia",
  "Semporna, Malaysia",
  "Rawang, Malaysia",
  "Sungai Petani, Malaysia",
  "Kajang, Malaysia",
  "Selayang, Malaysia",
  "Taiping, Malaysia",
  "Seremban, Malaysia",
  // Add more mock places
];

export default mockPlaces;
